### ISSUE TITLE
License, updates?

### ISSUE THREAD

**Issue by johann-petrak** [stanfordroboticsclub/UDPComms#5]
I would like to use this software in a project, however, there are quite a number of things I would like to change first (e.g. not needing sudo for installation, format of data to be transferred and a few more).

So I am wondering: what is the license or otherwise the condition to use this and possibly publish it in modified form? 

Since there have been no updates to this repository for quite a while, should suggestions for improvement get provided as issues or PRs or would it be fine to just work on a copy of the code?

Thanks for sharing the software.

**Comment by mikh3x4** [comment]
Thank for your interest in the library.

I've added an MIT licence to the repository. Its a permissive licence that allows you to freely change republish/not republish/use commercially the code.

I think the most practical will be if you fork the code repository and work on our own copy. I'd be super happy to see the changes you make and think about incorporating them upstream if you are happy with having the forked repository be public.

**Comment by johann-petrak** [comment]
Thank you for that information and adding the MIT license!
